# Generated by Django 4.1.5 on 2023-01-19 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("friendship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendshiprequest",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="friendshiprequest",
            name="from_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendship_requests_sent",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendshiprequest",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="friendshiprequest",
            name="rejected",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="friendshiprequest",
            name="to_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendship_requests_received",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendshiprequest",
            name="viewed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="friendshiprequest",
            unique_together={("from_user", "to_user")},
        ),
        migrations.RemoveField(
            model_name="friendshiprequest",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="friendshiprequest",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="friendshiprequest",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="friendshiprequest",
            name="updated_at",
        ),
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unaccepted_friend_relation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
