# Generated by Django 4.1.5 on 2023-01-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friendship", "0002_friendshiprequest_created_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FriendshipRequest",
        ),
    ]
