# Generated by Django 4.1.5 on 2023-01-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="wakeappuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="wakeappprofile",
            name="username",
        ),
        migrations.RemoveField(
            model_name="wakeappuser",
            name="email",
        ),
        migrations.AddField(
            model_name="wakeappprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="wakeappuser",
            name="username",
            field=models.CharField(default=1, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
